try {
    //let x = noExiste()
    throw "Error de programa"
} catch (error) {
    alert(error)

}



